import Head from "next/head";
import Container from "react-bootstrap/Container";
import AppGuides from "@/components/AppGuides";
import Footer from "@/components/Footer";
import NavigationBar from "@/components/NavigationBar";
import ItemsList from "@/components/ItemsList";
import UsersList from "@/components/UsersList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto">
        <NavigationBar shopListName="Drugstore" />

        <h1>Build Bootstrap with React</h1>

        <ItemsList />
        <div className="divider"></div>
        <UsersList />
        <hr className="col-1 my-5 mx-0" />

        <AppGuides />
        <Footer />
      </Container>
    </>
  );
}
