//index.tsx
import Head from "next/head";
import React, { useState, useEffect } from "react";
import Container from "react-bootstrap/Container";
import Footer from "@/components/Footer";

import NavigationBar from "@/components/NavigationBar";
import ItemsList from "@/components/ItemsList";
import UsersList from "@/components/UsersList";
import SettingsList from "@/components/SettingsList";
import { fetchShoppingList } from "@/api/ShoppingListApi";

export default function Home() {
    const [shoppingList, setShoppingList] = useState<{ id: number, name: string, owner: string, users: any[], items: any[] } | null>(null);
    
    useEffect(() => {
      async function loadData() {
        const list = await fetchShoppingList();
        setShoppingList(list);
      }
      loadData();
    }, []);

  return (
    <>
      <Head>
        <title>Shopping List app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="node_modules/bootstrap-icons/font/bootstrap-icons.css" />

      </Head>
        {shoppingList && <NavigationBar shopListName={shoppingList.name} />}
      <Container>
      <div>
      {/* <h1>Shopping List Name: {shoppingList ? shoppingList.name : "Loading..."}</h1> */}
    </div>
        <div className="my-3 p-3 bg-body rounded shadow-sm">
          {shoppingList && < ItemsList items={shoppingList.items} />}
        </div>

        <div className="my-3 p-3 bg-body rounded shadow-sm">
          <h3 className="border-bottom pb-2 mb-0">Users</h3>
          {shoppingList && <UsersList users={shoppingList.users} />}
        </div>

        <div className="my-3 p-3 bg-body rounded shadow-sm">
          <h3 className="border-bottom pb-2 mb-0">Setting</h3>
          {/* <SettingsList
            shopListName={shoppingList.name}
            setShopListName={setShopListName}
          /> */}
        </div>
        <Footer />
      </Container>
    </>
  );
}
